import type { Metadata } from "next";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut
 
} from '@clerk/nextjs'
import './globals.css'



export const metadata: Metadata = {
  title: "PDF-licker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <SignedOut>
          <SignInButton />
        </SignedOut>
        <SignedIn>
         
        </SignedIn>
        {children}
      </body>
    </html>
  </ClerkProvider>
  );
}
