import type { Metadata } from "next";

import {
  ClerkProvider,
 
 
} from '@clerk/nextjs'
import './globals.css'
import Providers from "../components/ui/Providers";
import {Toaster} from 'react-hot-toast'


export const metadata: Metadata = {
  title: "ChatDoc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Providers>
    <html lang="en">
      <body>
       
        {children}
      </body>
      <Toaster/>
    </html>
    
    </Providers>
  </ClerkProvider>
  );
}
